
export const Flowerlist = [
    {
        id:1,
        name:'roz',
        color:'red',
        price:'3000T'
    },
    {
        id:2,
        name:'maryam',
        color:'white',
        price:'350T'
    },
    {
        id:3,
        name:'yas',
        color:'white',
        price:'1000'
    },
    {
        id:4,
        name:'davoodi',
        color:'green',
        price:'2000T'
    },
    {
        id:5,
        name:'susan',
        color:'white',
        price:'5000T'
    },
    {
        id:6,
        name:'nastaran',
        color:'red',
        price:'4000T'
    },
    {
        id:7,
        name:'narges',
        color:'black',
        price:'1500T'
    },
    {
        id:8,
        name:'sorkh',
        color:'red',
        price:'3000T'
    },
    {
        id:9,
        name:'kaktose',
        color:'green',
        price:'4500T'
    },
    {
        id:10,
        name:'zarin',
        color:'red',
        price:'2500T'
    }
]

